theme: jekyll-theme-cayman
title: Morphe Artifacts
description: Pre‑patched YouTube & YT Music APKs — safer, ad‑free and premium features unlocked.
baseurl: /MorpheApp-Artifacts
show_downloads: false
plugins:
  - jekyll-sitemap
